services:
  core_api:
    build: .
    container_name: "news_analyzer"
    ports:
      - "8000:8000"
  db:
    image: postgres:15-alpine
    container_name: "postgres_db"
    environment:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
